# Generated by Django 5.0.8 on 2024-08-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="tg_id",
            field=models.CharField(
                blank=True, null=True, verbose_name="айди телеграмм"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.PositiveSmallIntegerField(verbose_name="Время"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time_to_complete",
            field=models.PositiveSmallIntegerField(
                default=120, verbose_name="время на выполнение привычки"
            ),
        ),
    ]
